name: Slack Test

on:
  push:
    branches:
      - "dev"
      - "master"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nelonoel/branch-name@v1.0.1
    - name: No Job Status
      id: job_eval_no_job_status
      if: ${{ always() }}
      uses: kaisalmen/evaluate-overall-status-action@v1
      with:
        ignore_test_report: true
    - name: Notify No Job Status
      if: ${{ always() }}
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel_id: '#gha-testing'
        status: ${{ steps.job_eval_no_job_status.outputs.overall_status }}
        color: ${{ steps.job_eval_no_job_status.outputs.overall_status_color }}
    - name: Wrong Job Status
      id: job_eval_wrong_job_status
      if: ${{ always() }}
      uses: kaisalmen/evaluate-overall-status-action@v1
      with:
        job_status: "cheese"
        ignore_test_report: true
    - name: Notify Wrong Job Status
      if: ${{ always() }}
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel_id: '#gha-testing'
        status: ${{ steps.job_eval_wrong_job_status.outputs.overall_status }}
        color: ${{ steps.job_eval_wrong_job_status.outputs.overall_status_color }}
    - name: Test Report Error
      id: job_eval_test_error
      if: ${{ always() }}
      uses: kaisalmen/evaluate-overall-status-action@v1
      with:
        job_status: "success"
        test_report_conclusion: ""
    - name: Notify Test Report Error
      if: ${{ always() }}
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel_id: '#gha-testing'
        status: ${{ steps.job_eval_test_error.outputs.overall_status }}
        color: ${{ steps.job_eval_test_error.outputs.overall_status_color }}
    - name: Report Wrong
      id: job_eval_test_report_wrong
      if: ${{ always() }}
      uses: kaisalmen/evaluate-overall-status-action@v1
      with:
        job_status: "success"
        test_report_conclusion: "sausage"
    - name: Notify Report Wrong
      if: ${{ always() }}
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel_id: '#gha-testing'
        status: ${{ steps.job_eval_test_report_wrong.outputs.overall_status }}
        color: ${{ steps.job_eval_test_report_wrong.outputs.overall_status_color }}
    - name: Job Success
      id: job_eval_job_success
      if: ${{ always() }}
      uses: kaisalmen/evaluate-overall-status-action@v1
      with:
        job_status: "success"
        test_report_conclusion: "success"
    - name: Notify Job Success
      if: ${{ always() }}
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel_id: '#gha-testing'
        status: ${{ steps.job_eval_job_success.outputs.overall_status }}
        color: ${{ steps.job_eval_job_success.outputs.overall_status_color }}
    - name: Job Failure
      id: job_eval_job_failure
      if: ${{ always() }}
      uses: kaisalmen/evaluate-overall-status-action@v1
      with:
        job_status: "failure"
        test_report_conclusion: "success"
    - name: Notify Job Failure
      if: ${{ always() }}
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel_id: '#gha-testing'
        status: ${{ steps.job_eval_job_failure.outputs.overall_status }}
        color: ${{ steps.job_eval_job_failure.outputs.overall_status_color }}
    - name: Make Green^
      if: ${{ always() }}
      run: exit 0
